# Generated by Django 5.2.6 on 2025-10-08 06:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('category', models.CharField(choices=[('reflection', 'Reflection'), ('gratitude', 'Gratitude'), ('goals', 'Goals'), ('relationships', 'Relationships'), ('creativity', 'Creativity'), ('wellness', 'Wellness'), ('career', 'Career'), ('learning', 'Learning')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'prompt_text'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('mood', models.CharField(choices=[('very_happy', 'Very Happy'), ('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('very_sad', 'Very Sad'), ('stressed', 'Stressed'), ('anxious', 'Anxious'), ('excited', 'Excited'), ('grateful', 'Grateful'), ('motivated', 'Motivated'), ('tired', 'Tired'), ('frustrated', 'Frustrated')], default='neutral', max_length=20)),
                ('weather', models.CharField(blank=True, choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('snowy', 'Snowy'), ('stormy', 'Stormy'), ('foggy', 'Foggy')], max_length=20)),
                ('energy_level', models.PositiveIntegerField(default=5, help_text='Energy level from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('productivity_score', models.PositiveIntegerField(default=5, help_text='Productivity score from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_private', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='journal_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='journal.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='JournalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('template_content', models.TextField(help_text='Template with placeholders like {date}, {mood}')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'date'], name='journal_jou_user_id_601e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'mood'], name='journal_jou_user_id_8668cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('user', 'date')},
        ),
    ]
