# Generated by Django 5.2.6 on 2025-10-08 06:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('health', 'Health'), ('fitness', 'Fitness'), ('learning', 'Learning'), ('productivity', 'Productivity'), ('mindfulness', 'Mindfulness'), ('social', 'Social'), ('creative', 'Creative'), ('financial', 'Financial'), ('other', 'Other')], default='other', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('target_count', models.PositiveIntegerField(default=1, help_text='Target completions per frequency period')),
                ('unit', models.CharField(blank=True, help_text="Unit of measurement (e.g., 'pages', 'minutes', 'glasses')", max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for the habit', null=True)),
                ('reminder_time', models.TimeField(blank=True, help_text='Daily reminder time', null=True)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity completed (e.g., 2 glasses of water)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='habits.habit')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HabitReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.TimeField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='habits.habit')),
            ],
        ),
        migrations.CreateModel(
            name='HabitStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('length', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='habits.habit')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_active'], name='habits_habi_user_id_f5e729_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'category'], name='habits_habi_user_id_35e2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcompletion',
            index=models.Index(fields=['habit', 'date'], name='habits_habi_habit_i_c12b65_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcompletion',
            index=models.Index(fields=['habit', 'completed'], name='habits_habi_habit_i_6a6988_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habitcompletion',
            unique_together={('habit', 'date')},
        ),
    ]
