# Generated by Django 5.2.6 on 2026-04-03 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitcompletion',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='habit',
            name='habits_habi_user_id_f5e729_idx',
        ),
        migrations.RemoveIndex(
            model_name='habit',
            name='habits_habi_user_id_35e2ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='habitcompletion',
            name='habits_habi_habit_i_c12b65_idx',
        ),
        migrations.RemoveIndex(
            model_name='habitcompletion',
            name='habits_habi_habit_i_6a6988_idx',
        ),
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('fitness', 'Fitness'), ('learning', 'Learning'), ('mindfulness', 'Mindfulness'), ('productivity', 'Productivity'), ('personal', 'Personal'), ('other', 'Other')], default='personal', max_length=30),
        ),
        migrations.AlterField(
            model_name='habit',
            name='color',
            field=models.CharField(blank=True, default='#007bff', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='target_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='unit',
            field=models.CharField(blank=True, default='times', max_length=50),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habitreminder',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='habitstreak',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitstreak',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='habitstreak',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
