# Generated by Django 5.2.6 on 2025-10-08 06:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_layout', models.CharField(choices=[('grid', 'Grid Layout'), ('list', 'List Layout')], default='grid', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('task_reminders', models.BooleanField(default=True)),
                ('habit_reminders', models.BooleanField(default=True)),
                ('journal_reminders', models.BooleanField(default=True)),
                ('share_analytics', models.BooleanField(default=False)),
                ('public_profile', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German')], default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('task_summary', 'Task Summary'), ('habit_tracker', 'Habit Tracker'), ('mood_chart', 'Mood Chart'), ('productivity_chart', 'Productivity Chart'), ('recent_journal', 'Recent Journal Entries'), ('upcoming_tasks', 'Upcoming Tasks'), ('streak_counter', 'Streak Counter'), ('quote_of_day', 'Quote of the Day')], max_length=20)),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=4)),
                ('height', models.PositiveIntegerField(default=3)),
                ('is_visible', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position_y', 'position_x'],
                'unique_together': {('user', 'widget_type')},
            },
        ),
        migrations.CreateModel(
            name='UserQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seen', models.DateField(default=django.utils.timezone.now)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.motivationalquote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quote', 'date_seen')},
            },
        ),
    ]
